### ISSUE TITLE
Verdi-SX 실행 관련한 문제 질문드립니다.

### ISSUE THREAD

**Issue by esmjihwankim** [2023-Spring-ECE4278/lab6#1]
안녕하세요, Verdi로 보는 방법에 대해 질문드립니다. Synthesis 는 완료하였고, 생성된 

lab6/DMAC/SYN/OUTPUT/

에서 Verdi-SX를 실행하면 라이선스 문제가 뜨는데 이 부분은 어떻게 해결하면 되는것일까요? 라이센서 관련해서 앞쪽 슬라이드의 코드인 

export SNPSLMD_LICENSE_FILE=27020@115.145.208.242:27000@semi-lic.skku.edu

이 부분을 실행하지 않아서 문제가 되는걸까요? 

Verdi-SX 실행로그 아래에 첨부드립니다. 

![image](https://user-images.githubusercontent.com/39392336/234182773-fd886cac-ab11-4a7c-887a-22dd535b860b.png)

감사합니다 :-)

**Comment by Park-So-Young** [comment]
교안에 업데이트를 반영하지 못하였는데, 수업 시간에 말씀드린 것처럼 Verdi-SX가 아니라 Verdi로 실행해주셔야 합니다. 
라이센스 경로는 이미 설정되어 있어서 추가적으로 export하지 않으셔도 됩니다.
