### ISSUE TITLE
lab6 verdi schema 관련 질문입니다. 

### ISSUE THREAD

**Issue by Malbulkup0413** [2023-Spring-ECE4278/lab6#2]
안녕하십니까, lab6 verdi schema로 critical path를 표현하는데 어려움이 있어 질문 드리게 되었습니다. 

$ Verdi를 실행한 후 verdi 창에서 DMAC_TOP.netlist.v 파일을 불러왔습니다. 

그 다음 scheme를 띄우게 되면 전체 logic에 대한 schema가 나타나게 됩니다. 

수업 때 보여주셨던 것처럼 신호 하나하나에 대해 schema를 보고 싶으면 어떻게 해야 되는지 궁금합니다. 

<img width="642" alt="scheme" src="https://user-images.githubusercontent.com/130634673/234527256-023b88ae-cb32-4bee-b1c9-6ac7fa49d9ff.png">
(전체 scheme 그림입니다. 위 그림에서 제가 원하는 logic만 남도록 scheme를 출력하고 싶습니다. )

감사합니다.

**Comment by Park-So-Young** [comment]
netlist에서 확인하고 싶으신 cell(신호)에 오른쪽 클릭하신 후 "New Schematic>>Driver"의 순서대로 하시면 됩니다.

**Comment by Malbulkup0413** [comment]
확인 감사합니다.
